# Generated by Django 6.0.3 on 2026-03-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0002_alter_movie_actors_alter_movie_genres_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="ticket",
            name="unique_ticket",
        ),
        migrations.RenameField(
            model_name="ticket",
            old_name="seats",
            new_name="seat",
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                fields=("row", "seat", "movie_session"), name="unique_ticket"
            ),
        ),
    ]
